alias: Homekit - Sensor Collection
description: Processes temperature and humidity data from the HomePod Mini
trigger:
  platform: time_pattern
  minutes: "/2"
id: time
action:
  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.homekit_sensors_update
  - delay: "00:00:05"
  - service: input_boolean.turn_off
    target:
      entity_id: input_boolean.homekit_sensors_update
mode: single
